/* NOTE this is not a header file; it is a source
	file fragment. it contains code that belongs in z80.cpp
	to define the opcode sizes and has been extracted
	to this file for easier maintenance. */
m_ed_opcode_size[Z80__ED__NOP__0XED__0X00] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X01] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X02] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X03] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X04] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X05] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X06] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X07] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0X08] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X09] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X0A] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X0B] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X0C] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X0D] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X0E] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X0F] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0X10] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X11] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X12] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X13] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X14] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X15] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X16] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X17] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0X18] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X19] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X1A] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X1B] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X1C] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X1D] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X1E] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X1F] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0X20] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X21] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X22] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X23] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X24] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X25] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X26] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X27] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0X28] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X29] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X2A] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X2B] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X2C] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X2D] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X2E] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X2F] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0X30] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X31] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X32] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X33] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X34] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X35] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X36] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X37] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0X38] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X39] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X3A] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X3B] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X3C] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X3D] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X3E] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X3F] = 2;

m_ed_opcode_size[Z80__ED__IN__B__INDIRECT_C] = 2;
m_ed_opcode_size[Z80__ED__OUT__INDIRECT_C__B] = 2;
m_ed_opcode_size[Z80__ED__SBC__HL__BC] = 2;
m_ed_opcode_size[Z80__ED__LD__INDIRECT_NN__BC] = 4;
m_ed_opcode_size[Z80__ED__NEG] = 2;
m_ed_opcode_size[Z80__ED__RETN] = 2;
m_ed_opcode_size[Z80__ED__IM__0] = 2;
m_ed_opcode_size[Z80__ED__LD__I__A] = 2;

m_ed_opcode_size[Z80__ED__IN__C__INDIRECT_C] = 2;
m_ed_opcode_size[Z80__ED__OUT__INDIRECT_C__C] = 2;
m_ed_opcode_size[Z80__ED__ADC__HL__BC] = 2;
m_ed_opcode_size[Z80__ED__LD__BC__INDIRECT_NN] = 4;
m_ed_opcode_size[Z80__ED__NEG__0XED__0X4C] = 2;
m_ed_opcode_size[Z80__ED__RETI] = 2;
m_ed_opcode_size[Z80__ED__IM__0__0XED__0X4E] = 2;
m_ed_opcode_size[Z80__ED__LD__R__A] = 2;

m_ed_opcode_size[Z80__ED__IN__D__INDIRECT_C] = 2;
m_ed_opcode_size[Z80__ED__OUT__INDIRECT_C__D] = 2;
m_ed_opcode_size[Z80__ED__SBC__HL__DE] = 2;
m_ed_opcode_size[Z80__ED__LD__INDIRECT_NN__DE] = 4;
m_ed_opcode_size[Z80__ED__NEG__0XED__0X54] = 2;
m_ed_opcode_size[Z80__ED__RETN__0XED__0X55] = 2;
m_ed_opcode_size[Z80__ED__IM__1] = 2;
m_ed_opcode_size[Z80__ED__LD__A__I] = 2;

m_ed_opcode_size[Z80__ED__IN__E__INDIRECT_C] = 2;
m_ed_opcode_size[Z80__ED__OUT__INDIRECT_C__E] = 2;
m_ed_opcode_size[Z80__ED__ADC__HL__DE] = 2;
m_ed_opcode_size[Z80__ED__LD__DE__INDIRECT_NN] = 4;
m_ed_opcode_size[Z80__ED__NEG__0XED__0X5C] = 2;
m_ed_opcode_size[Z80__ED__RETI__0XED__0X5D] = 2;
m_ed_opcode_size[Z80__ED__IM__2] = 2;
m_ed_opcode_size[Z80__ED__LD__A__R] = 2;

m_ed_opcode_size[Z80__ED__IN__H__INDIRECT_C] = 2;
m_ed_opcode_size[Z80__ED__OUT__INDIRECT_C__H] = 2;
m_ed_opcode_size[Z80__ED__SBC__HL__HL] = 2;
m_ed_opcode_size[Z80__ED__LD__INDIRECT_NN__HL] = 4;
m_ed_opcode_size[Z80__ED__NEG__0XED__0X64] = 2;
m_ed_opcode_size[Z80__ED__RETN__0XED__0X65] = 2;
m_ed_opcode_size[Z80__ED__IM__0__0XED__0X66] = 2;
m_ed_opcode_size[Z80__ED__RRD] = 2;

m_ed_opcode_size[Z80__ED__IN__L__INDIRECT_C] = 2;
m_ed_opcode_size[Z80__ED__OUT__INDIRECT_C__L] = 2;
m_ed_opcode_size[Z80__ED__ADC__HL__HL] = 2;
m_ed_opcode_size[Z80__ED__LD__HL__INDIRECT_NN] = 4;
m_ed_opcode_size[Z80__ED__NEG__0XED__0X6C] = 2;
m_ed_opcode_size[Z80__ED__RETI__0XED__0X6D] = 2;
m_ed_opcode_size[Z80__ED__IM__0__0XED__0X6E] = 2;
m_ed_opcode_size[Z80__ED__RLD] = 2;

m_ed_opcode_size[Z80__ED__IN__INDIRECT_C] = 2;
m_ed_opcode_size[Z80__ED__OUT__INDIRECT_C__0] = 2;
m_ed_opcode_size[Z80__ED__SBC__HL__SP] = 2;
m_ed_opcode_size[Z80__ED__LD__INDIRECT_NN__SP] = 4;
m_ed_opcode_size[Z80__ED__NEG__0XED__0X74] = 2;
m_ed_opcode_size[Z80__ED__RETN__0XED__0X75] = 2;
m_ed_opcode_size[Z80__ED__IM__1__0XED__0X76] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0x77] = 2;

m_ed_opcode_size[Z80__ED__IN__A__INDIRECT_C] = 2;
m_ed_opcode_size[Z80__ED__OUT__INDIRECT_C__A] = 2;
m_ed_opcode_size[Z80__ED__ADC__HL__SP] = 2;
m_ed_opcode_size[Z80__ED__LD__SP__INDIRECT_NN] = 4;
m_ed_opcode_size[Z80__ED__NEG__0XED__0X7C] = 2;
m_ed_opcode_size[Z80__ED__RETI__0XED__0X7D] = 2;
m_ed_opcode_size[Z80__ED__IM__2__0XED__0X7E] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X7F] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0X80] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X81] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X82] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X83] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X84] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X85] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X86] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X87] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0X88] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X89] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X8A] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X8B] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X8C] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X8D] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X8E] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X8F] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0X90] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X91] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X92] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X93] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X94] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X95] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X96] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X97] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0X98] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X99] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X9A] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X9B] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X9C] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X9D] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X9E] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0X9F] = 2;

m_ed_opcode_size[Z80__ED__LDI] = 2;
m_ed_opcode_size[Z80__ED__CPI] = 2;
m_ed_opcode_size[Z80__ED__INI] = 2;
m_ed_opcode_size[Z80__ED__OUTI] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XA4] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XA5] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XA6] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XA7] = 2;

m_ed_opcode_size[Z80__ED__LDD] = 2;
m_ed_opcode_size[Z80__ED__CPD] = 2;
m_ed_opcode_size[Z80__ED__IND] = 2;
m_ed_opcode_size[Z80__ED__OUTD] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XAC] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XAD] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XAE] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XAF] = 2;

m_ed_opcode_size[Z80__ED__LDIR]= 2;
m_ed_opcode_size[Z80__ED__CPIR]= 2;
m_ed_opcode_size[Z80__ED__INIR]= 2;
m_ed_opcode_size[Z80__ED__OTIR]= 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XB4] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XB5] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XB6] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XB7] = 2;

m_ed_opcode_size[Z80__ED__LDDR]= 2;
m_ed_opcode_size[Z80__ED__CPDR]= 2;
m_ed_opcode_size[Z80__ED__INDR]= 2;
m_ed_opcode_size[Z80__ED__OTDR]= 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XBC] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XBD] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XBE] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XBF] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0XC0] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XC1] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XC2] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XC3] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XC4] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XC5] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XC6] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XC7] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0XC8] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XC9] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XCA] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XCB] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XCC] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XCD] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XCE] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XCF] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0XD0] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XD1] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XD2] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XD3] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XD4] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XD5] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XD6] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XD7] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0XD8] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XD9] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XDA] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XDB] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XDC] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XDD] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XDE] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XDF] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0XE0] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XE1] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XE2] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XE3] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XE4] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XE5] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XE6] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XE7] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0XE8] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XE9] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XEA] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XEB] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XEC] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XED] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XEE] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XEF] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0XF0] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XF1] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XF2] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XF3] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XF4] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XF5] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XF6] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XF7] = 2;

m_ed_opcode_size[Z80__ED__NOP__0XED__0XF8] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XF9] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XFA] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XFB] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XFC] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XFD] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XFE] = 2;
m_ed_opcode_size[Z80__ED__NOP__0XED__0XFF] = 2;
