// t-state costs of opcodes prefixed with 0xcb

8,        // Z80__CB__RLC__B
8,        // Z80__CB__RLC__C
8,        // Z80__CB__RLC__D
8,        // Z80__CB__RLC__E
8,        // Z80__CB__RLC__H
8,        // Z80__CB__RLC__L
15,        // Z80__CB__RLC__INDIRECT_HL
8,        // Z80__CB__RLC__A

8,        // Z80__CB__RRC__B
8,        // Z80__CB__RRC__C
8,        // Z80__CB__RRC__D
8,        // Z80__CB__RRC__E
8,        // Z80__CB__RRC__H
8,        // Z80__CB__RRC__L
15,        // Z80__CB__RRC__INDIRECT_HL
8,        // Z80__CB__RRC__A

8,        // Z80__CB__RL__B
8,        // Z80__CB__RL__C
8,        // Z80__CB__RL__D
8,        // Z80__CB__RL__E
8,        // Z80__CB__RL__H
8,        // Z80__CB__RL__L
15,        // Z80__CB__RL__INDIRECT_HL
8,        // Z80__CB__RL__A

8,        // Z80__CB__RR__B
8,        // Z80__CB__RR__C
8,        // Z80__CB__RR__D
8,        // Z80__CB__RR__E
8,        // Z80__CB__RR__H
8,        // Z80__CB__RR__L
15,        // Z80__CB__RR__INDIRECT_HL
8,        // Z80__CB__RR__A

8,        // Z80__CB__SLA__B
8,        // Z80__CB__SLA__C
8,        // Z80__CB__SLA__D
8,        // Z80__CB__SLA__E
8,        // Z80__CB__SLA__H
8,        // Z80__CB__SLA__L
15,        // Z80__CB__SLA__INDIRECT_HL
8,        // Z80__CB__SLA__A

8,        // Z80__CB__SRA__B
8,        // Z80__CB__SRA__C
8,        // Z80__CB__SRA__D
8,        // Z80__CB__SRA__E
8,        // Z80__CB__SRA__H
8,        // Z80__CB__SRA__L
15,        // Z80__CB__SRA__INDIRECT_HL
8,        // Z80__CB__SRA__A

8,        // Z80__CB__SLL__B
8,        // Z80__CB__SLL__C
8,        // Z80__CB__SLL__D
8,        // Z80__CB__SLL__E
8,        // Z80__CB__SLL__H
8,        // Z80__CB__SLL__L
15,        // Z80__CB__SLL__INDIRECT_HL
8,        // Z80__CB__SLL__A

8,        // Z80__CB__SRL__B
8,        // Z80__CB__SRL__C
8,        // Z80__CB__SRL__D
8,        // Z80__CB__SRL__E
8,        // Z80__CB__SRL__H
8,        // Z80__CB__SRL__L
15,        // Z80__CB__SRL__INDIRECT_HL
8,        // Z80__CB__SRL__A

8,        // Z80__CB__BIT__0__B
8,        // Z80__CB__BIT__0__C
8,        // Z80__CB__BIT__0__D
8,        // Z80__CB__BIT__0__E
8,        // Z80__CB__BIT__0__H
8,        // Z80__CB__BIT__0__L
12,        // Z80__CB__BIT__0__INDIRECT_HL
8,        // Z80__CB__BIT__0__A

8,        // Z80__CB__BIT__1__B
8,        // Z80__CB__BIT__1__C
8,        // Z80__CB__BIT__1__D
8,        // Z80__CB__BIT__1__E
8,        // Z80__CB__BIT__1__H
8,        // Z80__CB__BIT__1__L
12,        // Z80__CB__BIT__1__INDIRECT_HL
8,        // Z80__CB__BIT__1__A

8,        // Z80__CB__BIT__2__B
8,        // Z80__CB__BIT__2__C
8,        // Z80__CB__BIT__2__D
8,        // Z80__CB__BIT__2__E
8,        // Z80__CB__BIT__2__H
8,        // Z80__CB__BIT__2__L
12,        // Z80__CB__BIT__2__INDIRECT_HL
8,        // Z80__CB__BIT__2__A

8,        // Z80__CB__BIT__3__B
8,        // Z80__CB__BIT__3__C
8,        // Z80__CB__BIT__3__D
8,        // Z80__CB__BIT__3__E
8,        // Z80__CB__BIT__3__H
8,        // Z80__CB__BIT__3__L
12,        // Z80__CB__BIT__3__INDIRECT_HL
8,        // Z80__CB__BIT__3__A

8,        // Z80__CB__BIT__4__B
8,        // Z80__CB__BIT__4__C
8,        // Z80__CB__BIT__4__D
8,        // Z80__CB__BIT__4__E
8,        // Z80__CB__BIT__4__H
8,        // Z80__CB__BIT__4__L
12,        // Z80__CB__BIT__4__INDIRECT_HL
8,        // Z80__CB__BIT__4__A

8,        // Z80__CB__BIT__5__B
8,        // Z80__CB__BIT__5__C
8,        // Z80__CB__BIT__5__D
8,        // Z80__CB__BIT__5__E
8,        // Z80__CB__BIT__5__H
8,        // Z80__CB__BIT__5__L
12,        // Z80__CB__BIT__5__INDIRECT_HL
8,        // Z80__CB__BIT__5__A

8,        // Z80__CB__BIT__6__B
8,        // Z80__CB__BIT__6__C
8,        // Z80__CB__BIT__6__D
8,        // Z80__CB__BIT__6__E
8,        // Z80__CB__BIT__6__H
8,        // Z80__CB__BIT__6__L
12,        // Z80__CB__BIT__6__INDIRECT_HL
8,        // Z80__CB__BIT__6__A

8,        // Z80__CB__BIT__7__B
8,        // Z80__CB__BIT__7__C
8,        // Z80__CB__BIT__7__D
8,        // Z80__CB__BIT__7__E
8,        // Z80__CB__BIT__7__H
8,        // Z80__CB__BIT__7__L
12,        // Z80__CB__BIT__7__INDIRECT_HL
8,        // Z80__CB__BIT__7__A

8,        // Z80__CB__RES__0__B
8,        // Z80__CB__RES__0__C
8,        // Z80__CB__RES__0__D
8,        // Z80__CB__RES__0__E
8,        // Z80__CB__RES__0__H
8,        // Z80__CB__RES__0__L
15,        // Z80__CB__RES__0__INDIRECT_HL
8,        // Z80__CB__RES__0__A

8,        // Z80__CB__RES__1__B
8,        // Z80__CB__RES__1__C
8,        // Z80__CB__RES__1__D
8,        // Z80__CB__RES__1__E
8,        // Z80__CB__RES__1__H
8,        // Z80__CB__RES__1__L
15,        // Z80__CB__RES__1__INDIRECT_HL
8,        // Z80__CB__RES__1__A

8,        // Z80__CB__RES__2__B
8,        // Z80__CB__RES__2__C
8,        // Z80__CB__RES__2__D
8,        // Z80__CB__RES__2__E
8,        // Z80__CB__RES__2__H
8,        // Z80__CB__RES__2__L
15,        // Z80__CB__RES__2__INDIRECT_HL
8,        // Z80__CB__RES__2__A

8,        // Z80__CB__RES__3__B
8,        // Z80__CB__RES__3__C
8,        // Z80__CB__RES__3__D
8,        // Z80__CB__RES__3__E
8,        // Z80__CB__RES__3__H
8,        // Z80__CB__RES__3__L
15,        // Z80__CB__RES__3__INDIRECT_HL
8,        // Z80__CB__RES__3__A

8,        // Z80__CB__RES__4__B
8,        // Z80__CB__RES__4__C
8,        // Z80__CB__RES__4__D
8,        // Z80__CB__RES__4__E
8,        // Z80__CB__RES__4__H
8,        // Z80__CB__RES__4__L
15,        // Z80__CB__RES__4__INDIRECT_HL
8,        // Z80__CB__RES__4__A

8,        // Z80__CB__RES__5__B
8,        // Z80__CB__RES__5__C
8,        // Z80__CB__RES__5__D
8,        // Z80__CB__RES__5__E
8,        // Z80__CB__RES__5__H
8,        // Z80__CB__RES__5__L
15,        // Z80__CB__RES__5__INDIRECT_HL
8,        // Z80__CB__RES__5__A

8,        // Z80__CB__RES__6__B
8,        // Z80__CB__RES__6__C
8,        // Z80__CB__RES__6__D
8,        // Z80__CB__RES__6__E
8,        // Z80__CB__RES__6__H
8,        // Z80__CB__RES__6__L
15,        // Z80__CB__RES__6__INDIRECT_HL
8,        // Z80__CB__RES__6__A

8,        // Z80__CB__RES__7__B
8,        // Z80__CB__RES__7__C
8,        // Z80__CB__RES__7__D
8,        // Z80__CB__RES__7__E
8,        // Z80__CB__RES__7__H
8,        // Z80__CB__RES__7__L
15,        // Z80__CB__RES__7__INDIRECT_HL
8,        // Z80__CB__RES__7__A

8,        // Z80__CB__SET__0__B
8,        // Z80__CB__SET__0__C
8,        // Z80__CB__SET__0__D
8,        // Z80__CB__SET__0__E
8,        // Z80__CB__SET__0__H
8,        // Z80__CB__SET__0__L
15,        // Z80__CB__SET__0__INDIRECT_HL
8,        // Z80__CB__SET__0__A

8,        // Z80__CB__SET__1__B
8,        // Z80__CB__SET__1__C
8,        // Z80__CB__SET__1__D
8,        // Z80__CB__SET__1__E
8,        // Z80__CB__SET__1__H
8,        // Z80__CB__SET__1__L
15,        // Z80__CB__SET__1__INDIRECT_HL
8,        // Z80__CB__SET__1__A

8,        // Z80__CB__SET__2__B
8,        // Z80__CB__SET__2__C
8,        // Z80__CB__SET__2__D
8,        // Z80__CB__SET__2__E
8,        // Z80__CB__SET__2__H
8,        // Z80__CB__SET__2__L
15,        // Z80__CB__SET__2__INDIRECT_HL
8,        // Z80__CB__SET__2__A

8,        // Z80__CB__SET__3__B
8,        // Z80__CB__SET__3__C
8,        // Z80__CB__SET__3__D
8,        // Z80__CB__SET__3__E
8,        // Z80__CB__SET__3__H
8,        // Z80__CB__SET__3__L
15,        // Z80__CB__SET__3__INDIRECT_HL
8,        // Z80__CB__SET__3__A

8,        // Z80__CB__SET__4__B
8,        // Z80__CB__SET__4__C
8,        // Z80__CB__SET__4__D
8,        // Z80__CB__SET__4__E
8,        // Z80__CB__SET__4__H
8,        // Z80__CB__SET__4__L
15,        // Z80__CB__SET__4__INDIRECT_HL
8,        // Z80__CB__SET__4__A

8,        // Z80__CB__SET__5__B
8,        // Z80__CB__SET__5__C
8,        // Z80__CB__SET__5__D
8,        // Z80__CB__SET__5__E
8,        // Z80__CB__SET__5__H
8,        // Z80__CB__SET__5__L
15,        // Z80__CB__SET__5__INDIRECT_HL
8,        // Z80__CB__SET__5__A

8,        // Z80__CB__SET__6__B
8,        // Z80__CB__SET__6__C
8,        // Z80__CB__SET__6__D
8,        // Z80__CB__SET__6__E
8,        // Z80__CB__SET__6__H
8,        // Z80__CB__SET__6__L
15,        // Z80__CB__SET__6__INDIRECT_HL
8,        // Z80__CB__SET__6__A

8,        // Z80__CB__SET__7__B
8,        // Z80__CB__SET__7__C
8,        // Z80__CB__SET__7__D
8,        // Z80__CB__SET__7__E
8,        // Z80__CB__SET__7__H
8,        // Z80__CB__SET__7__L
15,        // Z80__CB__SET__7__INDIRECT_HL
8,        // Z80__CB__SET__7__A
